version: 4.3.3
name: WaifuRPG
description: Transform your RPG's with WaifuRPG
url: https://rpg.ruinedmango.com
repository: https://github.com/RuinedMango/WaifuRPG
timezone: America/Los_Angeles
github:
  username: ruinedmango
future: true
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
feed:
  categories:
    - release
kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
sass:
  style: compressed
strict_front_matter: true
exclude:
  - readme.md